### ISSUE TITLE
uses multiple redirect_uris

### ISSUE THREAD

**Issue by fkooman** [skddc/sharesome#39]
I noticed that multiple redirect URIs are used by sharesome, depending on the URL you are visiting. If you try to login while on the 'history' page it will use that as a `redirect_uri`, it should use `state` for that. Now I have the app listed twice ;)

![screenshot from 2015-10-27 21-00-06](https://cloud.githubusercontent.com/assets/616885/10770843/bcdfbc46-7ced-11e5-9e9b-429a0236383b.png)

**Comment by skddc** [comment]
I disagree. I'm using a proper router, so the redirect URI makes more sense to me here. For 5apps Storage, we use the *origin* as the client ID and apply the given redirect URI to every auth as long as its origin/host is the same as what we stored. The Web Platform (client-side) security model uses the origin, not specific URLs, as differentiator for site/app identity.
