### ISSUE TITLE
Update setup (ember-cli, dep versions etc.)

### ISSUE THREAD

**Issue by jorinvo** [skddc/sharesome#40]
I really like sharesome and I have some ideas to improve it.
Unfortunately, I can't work on it because I don't manage to set up the project.
First I need to install Ruby and Bundler. Then Bower (I already have node installed).
But I get some dependency conflicts running `npm install`.

Would it be possible to make the setup simpler? Are Bower and compass really necessary?

**Comment by skddc** [comment]
Glad you like it, and even better that you want to improve it! :)

I have to upgrade the whole setup soon. It's totally outdated. Not even using ember-cli as of yet. Will switch to node-sass then. You just pushed me over the edge for adding it to my main todo list.

**Comment by jorinvo** [comment]
@skddc thanks! Looking forward to give Ember a try!

**Comment by skddc** [comment]
Branch is here: https://github.com/skddc/sharesome/tree/the-big-upgrade

There are still a million deprecation warnings and tests are only green in browser, but not headless mode.

**Comment by skddc** [comment]
@jorinvo Shouldn't need anything other than `npm install` now, in order for `npm start` to fire up the app.

**Comment by jorinvo** [comment]
Nice work! However, while running `npm install` it crashes while doing the `bower install`.
I don't really understand the error, but maybe it helps you: https://gist.github.com/jorinvo/4f27dbb9f9b65704d5b8

**Comment by skddc** [comment]
That's a pretty old Bower. I added the latest stable version (1.7.2) to devDeps, so it should use that from the `postinstall` script now. Could you pull and try again?

**Comment by jorinvo** [comment]
That's surprising. I don't have bower installed globally so sharesome probably installed this bower version.
It's looking better now!
`npm install` looks good.

However running `npm start` I get an error: https://gist.github.com/jorinvo/a2ce1170de1488c39166
The thing with `watchman` should be fine but the error with the `node_modules` folder ...
With the latest `npm`, a lot of the sub-dependencies are reused and all installed in the same `node_modules` folder. So I guess there is some code running that was written for an older `npm` version...
Any ideas @skddc?

**Comment by jorinvo** [comment]
I installed `watchman`. But the error is still there: https://gist.github.com/jorinvo/a2ce1170de1488c39166

**Comment by skddc** [comment]
Sorry, no idea. But did you `rm -rf` your `node_modules` dir before trying again? For me that's usually the easiest fix for these types of conflicts. The message basically states that `ember-cli-moment` wasn't installed properly, because that one should have it's own `node_modules`.

**Comment by skddc** [comment]
... btw, this is exactly why npm drives me mad sometimes. And I'm sure I'm not the only one. ;)

**Comment by jorinvo** [comment]
@skddc which npm version are you using? Mine is `3.6.0`.

**Comment by jorinvo** [comment]
yes, dependencies are hard. But I think npm does a pretty good job compared to others. Had many problems with all of them bundler, pip, cabal, apt-get, homebrew, ...

**Comment by skddc** [comment]
Bundler never failed like this for me and my system's Pacman is just fantastic. :)

Anyway, I'm running node 5.0.0 and npm 3.3.10.

**Comment by skddc** [comment]
Note: install issues fixed after discussing on IRC, and @jorinvo adding `ember-moment` in favor of `ember-cli-moment` in #43.

**Comment by skddc** [comment]
I just moved the last views to components and merged the whole branch to master.
