### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by skddc** [skddc/sharesome#49]
I'd like to be able to search my shares (by filename at least, if we don't add user-editable meta information).

I'm sharing a lot of conversational images, and I'm just too lazy to scroll down and fish them out of the page, so I just share them again and again. By this point I have no idea how many duplicates there are.

Tags could also be useful when looking for a specific screenshot and such things for example. Or all shares about a certain project.

**Comment by galfert** [comment]
Yes, tagging would be super useful. Missing that quite often when searching for a picture.

**Comment by skddc** [comment]
A basic version of the search feature has been merged and deployed.

However, it doesn't yet load images dynamically, based on which are filtered, so the UX is not great yet. I'll open a seperate issue for it, and the solution belongs in the open #53 PR I think.
